
export const EVAL_QUESTIONS = [
  // 1. Direct questions
  { category: "direct", query: "What should I do first for a small cut that is bleeding?", expectedId: "bleed-001" },
  { category: "direct", query: "How can I manage a deep wound with heavy bleeding?", expectedId: "bleed-002" },
  { category: "direct", query: "How do I stop a nosebleed safely?", expectedId: "bleed-003" },
  { category: "direct", query: "What should I do if a permanent tooth gets knocked out?", expectedId: "bleed-004" },
  { category: "direct", query: "What is the first aid for a minor burn from hot water?", expectedId: "burn-001" },
  { category: "direct", query: "How should I respond to a serious burn with blistered or damaged skin?", expectedId: "burn-002" },
  { category: "direct", query: "What do I do if a cleaning chemical splashes into someone's eye?", expectedId: "burn-003" },
  { category: "direct", query: "What is the first aid for an adult who is choking?", expectedId: "choke-001" },
  { category: "direct", query: "How do I help a person who has been pulled from water and is not responding?", expectedId: "drowning-001" },
  { category: "direct", query: "How do I perform CPR on an adult who is unresponsive and not breathing normally?", expectedId: "cpr-001" },
  { category: "direct", query: "What are common warning signs of a heart attack?", expectedId: "heart-001" },
  { category: "direct", query: "What should I do if I think someone's arm is broken?", expectedId: "fracture-001" },
  { category: "direct", query: "How do I care for a sprained ankle?", expectedId: "sprain-001" },
  { category: "direct", query: "What should I do for suspected heatstroke?", expectedId: "heat-001" },
  { category: "direct", query: "What is the first aid for hypothermia?", expectedId: "hypothermia-001" },
  { category: "direct", query: "What should I do if someone swallowed a poisonous household product?", expectedId: "poison-001" },
  { category: "direct", query: "What are the signs of a drug overdose and what should I do?", expectedId: "overdose-001" },
  { category: "direct", query: "What should I do after a bee sting causes a severe allergic reaction?", expectedId: "allergy-001" },
  { category: "direct", query: "How can I recognize and respond to a seizure?", expectedId: "seizure-001" },
  { category: "direct", query: "What is the FAST method for recognizing a stroke?", expectedId: "stroke-001" },
  { category: "direct", query: "How should I place an unconscious person who is breathing normally?", expectedId: "recovery-001" },

  // 2. Indirect symptom descriptions
  { category: "indirect", query: "There is a steady stream of blood coming from a cut on my hand.", expectedId: "bleed-001" },
  { category: "indirect", query: "My nose has been bleeding for several minutes and won't stop.", expectedId: "bleed-003" },
  { category: "indirect", query: "A tooth came completely out after I fell.", expectedId: "bleed-004" },
  { category: "indirect", query: "My skin is red and painful after touching a hot pan.", expectedId: "burn-001" },
  { category: "indirect", query: "Someone swallowed a bottle of cleaning liquid by mistake.", expectedId: "poison-001" },
  { category: "indirect", query: "My friend took far more tablets than the label says.", expectedId: "overdose-001" },
  { category: "indirect", query: "A person is clutching their chest and looks sweaty and breathless.", expectedId: "heart-001" },
  { category: "indirect", query: "Someone is making choking sounds and cannot speak or cough effectively.", expectedId: "choke-001" },
  { category: "indirect", query: "A person was in a pool, has been brought out, and is barely responsive.", expectedId: "drowning-001" },
  { category: "indirect", query: "My ankle twisted while running and is now swollen and painful.", expectedId: "sprain-001" },
  { category: "indirect", query: "After a fall, the forearm looks deformed and hurts to move.", expectedId: "fracture-001" },
  { category: "indirect", query: "Someone has been in the sun for hours and is confused and very hot.", expectedId: "heat-001" },
  { category: "indirect", query: "A person exposed to cold is shivering, clumsy, and unusually drowsy.", expectedId: "hypothermia-001" },
  { category: "indirect", query: "A wasp sting was followed by throat tightness and difficulty breathing.", expectedId: "allergy-001" },
  { category: "indirect", query: "One side of someone's face is drooping and their words sound slurred.", expectedId: "stroke-001" },
  { category: "indirect", query: "A child has a fever and suddenly starts jerking and becomes unresponsive.", expectedId: "pediatric-001" },
  { category: "indirect", query: "A person suddenly collapses but is breathing normally again.", expectedId: "faint-001" },
  { category: "indirect", query: "A person is breathing very fast and feels tingling around their mouth and fingers.", expectedId: "hyperventilation-001" },
  { category: "indirect", query: "A child has a fever, stiff neck, and is unusually difficult to wake.", expectedId: "pediatric-003" },
  { category: "indirect", query: "There is a painful red swelling around a tooth and pus near the gum.", expectedId: "dental-002" },
  { category: "indirect", query: "A pregnant person has a severe headache and visual disturbances.", expectedId: "pregnancy-002" },

  // 3. Emergency scenarios
  { category: "emergency", query: "A kitchen knife wound is bleeding heavily and blood is soaking through cloth.", expectedId: "bleed-002" },
  { category: "emergency", query: "A person has a severe burn after an electrical accident.", expectedId: "burn-004" },
  { category: "emergency", query: "A toddler is choking and cannot make sounds or breathe properly.", expectedId: "choke-002" },
  { category: "emergency", query: "An infant under one year cannot breathe because of food lodged in the airway.", expectedId: "choke-003" },
  { category: "emergency", query: "An adult is unresponsive and only gasping after collapsing.", expectedId: "cpr-001" },
  { category: "emergency", query: "A child is unresponsive and not breathing normally.", expectedId: "cpr-002" },
  { category: "emergency", query: "A baby is unresponsive and not breathing normally.", expectedId: "cpr-003" },
  { category: "emergency", query: "A person has stroke-like symptoms that started ten minutes ago.", expectedId: "stroke-001" },
  { category: "emergency", query: "After taking an unknown substance, someone is unconscious and breathing abnormally.", expectedId: "overdose-001" },
  { category: "emergency", query: "A person inhaled smoke from a faulty heater and has a headache and confusion.", expectedId: "co-001" },
  { category: "emergency", query: "Someone with diabetes is sweaty, shaky, and becoming confused.", expectedId: "diabetic-001" },
  { category: "emergency", query: "A person has a seizure on the floor and is striking nearby furniture.", expectedId: "seizure-001" },
  { category: "emergency", query: "A snake has bitten someone's leg while hiking.", expectedId: "snakebite-001" },
  { category: "emergency", query: "A person is bitten by an animal and the wound is deep.", expectedId: "animalbite-001" },
  { category: "emergency", query: "A person is in shock after an injury, with pale clammy skin and weakness.", expectedId: "shock-001" },
  { category: "emergency", query: "A person collapses in the heat and is confused with very hot skin.", expectedId: "heat-001" },
  { category: "emergency", query: "A pregnant person has a severe headache, high blood pressure concerns, and blurred vision.", expectedId: "pregnancy-002" },
  { category: "emergency", query: "A person in late pregnancy is bleeding and reports severe abdominal pain.", expectedId: "pregnancy-001" },
  { category: "emergency", query: "A person has sudden severe abdominal pain that is getting worse near the lower right side.", expectedId: "abdominal-001" },
  { category: "emergency", query: "A person has chest tightness, wheezing, and swelling of the lips after eating nuts.", expectedId: "allergy-001" },
  { category: "emergency", query: "Someone is unconscious after fainting but is now breathing normally.", expectedId: "recovery-001" },

  // 4. Out-of-scope questions
  { category: "out_of_scope", query: "How do I remove a coffee stain from a white shirt?", expectedId: null },
  { category: "out_of_scope", query: "What is the weather forecast for tomorrow?", expectedId: null },
  { category: "out_of_scope", query: "Can you recommend a laptop for computer science classes?", expectedId: null },
  { category: "out_of_scope", query: "Explain how to solve a quadratic equation.", expectedId: null },
  { category: "out_of_scope", query: "What is the capital city of Japan?", expectedId: null },
  { category: "out_of_scope", query: "Give me a recipe for chocolate brownies.", expectedId: null },
  { category: "out_of_scope", query: "How do I reset my Wi-Fi router?", expectedId: null },
  { category: "out_of_scope", query: "What is the best way to prepare for a coding interview?", expectedId: null },
  { category: "out_of_scope", query: "Write a birthday message for my friend.", expectedId: null },
  { category: "out_of_scope", query: "How do I clean mud off white sneakers?", expectedId: null },
  { category: "out_of_scope", query: "What are the rules of chess?", expectedId: null },
  { category: "out_of_scope", query: "Help me plan a weekend trip to Jaipur.", expectedId: null },
  { category: "out_of_scope", query: "How do I calculate compound interest?", expectedId: null },
  { category: "out_of_scope", query: "Which programming language should I learn first?", expectedId: null },
  { category: "out_of_scope", query: "What is the history of the Taj Mahal?", expectedId: null },
  { category: "out_of_scope", query: "How can I improve my resume?", expectedId: null },
  { category: "out_of_scope", query: "What is the difference between TCP and UDP?", expectedId: null },
  { category: "out_of_scope", query: "Suggest a vegetarian meal plan for the week.", expectedId: null },
  { category: "out_of_scope", query: "How do I remove a software package from my Mac?", expectedId: null },
  { category: "out_of_scope", query: "Can you explain the rules of cricket?", expectedId: null },
  { category: "out_of_scope", query: "How do I format a spreadsheet in Excel?", expectedId: null },

  // 5. Overlapping or similar symptoms
  { category: "overlap", query: "A bee sting caused hives, lip swelling, and trouble breathing.", expectedId: "allergy-001" },
  { category: "overlap", query: "A bee sting left a small sore spot, but there is no swelling elsewhere or breathing trouble.", expectedId: "sting-001" },
  { category: "overlap", query: "A person is breathing rapidly during fear and has tingling fingers, but no chest pain or fainting.", expectedId: "hyperventilation-001" },
  { category: "overlap", query: "A person has sudden chest pressure, sweating, and nausea while resting.", expectedId: "heart-001" },
  { category: "overlap", query: "A person feels intense fear with a racing heart, but has no new weakness or facial droop.", expectedId: "panic-001" },
  { category: "overlap", query: "A child has a fever and seizure-like movements, then becomes alert and returns to normal.", expectedId: "pediatric-001" },
  { category: "overlap", query: "A child has fever, stiff neck, and sensitivity to light without a seizure.", expectedId: "pediatric-003" },
  { category: "overlap", query: "An adult collapses briefly, wakes quickly, and is now breathing normally.", expectedId: "faint-001" },
  { category: "overlap", query: "An unconscious person is breathing normally and has no suspected spinal injury.", expectedId: "recovery-001" },
  { category: "overlap", query: "A person fell and has shoulder pain with an obvious joint deformity.", expectedId: "dislocation-001" },
  { category: "overlap", query: "A person fell and has pain and swelling over the wrist with possible bone injury.", expectedId: "fracture-001" },
  { category: "overlap", query: "A person rolled an ankle; it is swollen but not visibly deformed.", expectedId: "sprain-001" },
  { category: "overlap", query: "A child has a barking cough and noisy breathing that worsens at night.", expectedId: "pediatric-002" },
  { category: "overlap", query: "A person has a cough and fever with shortness of breath developing over days.", expectedId: "respiratory-001" },
  { category: "overlap", query: "A person has wheezing and shortness of breath during a known asthma attack.", expectedId: "asthma-001" },
  { category: "overlap", query: "A person has a high blood glucose reading and unusual thirst, without shakiness or sweating.", expectedId: "diabetic-002" },
  { category: "overlap", query: "A person with diabetes is shaky, sweaty, and has a low glucose reading.", expectedId: "diabetic-001" },
  { category: "overlap", query: "A painful blister appeared after new shoes rubbed the heel.", expectedId: "blister-001" },
  { category: "overlap", query: "A small wood splinter is lodged just under the skin of a finger.", expectedId: "splinter-001" },
  { category: "overlap", query: "A person has abdominal pain with vomiting but no clear injury.", expectedId: "stomach-001" },
  { category: "overlap", query: "A person has repeated vomiting and nausea without a clear cause.", expectedId: "vomiting-001" }
];
